### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Amadeus-** [Albeoris/MMXLegacy#1]
I really enjoyed Might and Magic X Legacy, so I was excited when I saw that you had a project related to it.    My question; however, is if you could provide a little more information as to what this project does.    Is it just a rewrite of the engine so that it looks/runs better, etc.?    Or, does this project/engine allow you to create additional content for the game (or edit the content that is included with the game.)

I was truly hoping that the developers would release the code necessary so that folks could make new adventures/stories for this game engine, as I think there is a lot of potential with the engine.

**Comment by Albeoris** [comment]
It allow us to create additional content for the game and edit existing.

**Comment by Albeoris** [comment]
**About current features:**

https://github.com/Albeoris/MMXLegacy/wiki

**Comment by Amadeus-** [comment]
Fantastic!   I'll reinstall the game and check out what you've done and see if I can contribute to the project.    I really enjoy this type of game engine and would like to see more like it in the future.
